services:
  db:
    image: postgres:15
    container_name: nsl_db_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nsl_db_password_2026
      - POSTGRES_DB=nsl_db
    ports:
      - "5433:5432"
    volumes:
      - nsl_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nsl_backend_container
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=nsl_db_password_2026
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/static:/app/backend/static

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: nsl_frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  nsl_db_data: