"""Add avatar store and ownership

Revision ID: 4cfb71215a84
Revises: 4d9631d6b776
Create Date: 2026-02-27 15:41:48.705218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfb71215a84'
down_revision: Union[str, Sequence[str], None] = '4d9631d6b776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avatars',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.add_column('avatars', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('coins', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('current_avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_stats', 'avatars', ['current_avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.drop_column('user_stats', 'current_avatar_id')
    op.drop_column('user_stats', 'coins')
    op.drop_column('avatars', 'price')
    op.drop_table('user_avatars')
    # ### end Alembic commands ###
