"""Fix avatar columns

Revision ID: 5fed8cf5455f
Revises: bdf959abf7f9
Create Date: 2026-02-27 14:27:42.483725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fed8cf5455f'
down_revision: Union[str, Sequence[str], None] = 'bdf959abf7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avatars', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('avatars', 'folder_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_avatars_name'), table_name='avatars')
    op.create_unique_constraint(None, 'avatars', ['name'])
    op.drop_column('avatars', 'model_url')
    op.drop_column('avatars', 'is_active')
    op.drop_column('avatars', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('model_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'avatars', type_='unique')
    op.create_index(op.f('ix_avatars_name'), 'avatars', ['name'], unique=True)
    op.alter_column('avatars', 'folder_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('avatars', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
