"""Add sign_code column to signs

Revision ID: 67a472721919
Revises: b035af81a6f0
Create Date: 2026-02-27 14:22:47.110454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a472721919'
down_revision: Union[str, Sequence[str], None] = 'b035af81a6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('folder_name', sa.String(), nullable=True))
    op.drop_column('avatars', 'model_url')
    op.drop_column('avatars', 'thumbnail_url')
    op.drop_column('avatars', 'is_active')
    op.add_column('signs', sa.Column('sign_code', sa.String(), nullable=True))
    op.alter_column('signs', 'nepali_char',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('signs', 'category',
               existing_type=postgresql.ENUM('VOWEL', 'CONSONANT', name='signcategory'),
               nullable=True)
    op.drop_constraint(op.f('signs_title_key'), 'signs', type_='unique')
    op.drop_column('signs', 'animation_name')
    op.drop_column('signs', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signs', sa.Column('animation_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('signs_title_key'), 'signs', ['title'], postgresql_nulls_not_distinct=False)
    op.alter_column('signs', 'category',
               existing_type=postgresql.ENUM('VOWEL', 'CONSONANT', name='signcategory'),
               nullable=False)
    op.alter_column('signs', 'nepali_char',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('signs', 'sign_code')
    op.add_column('avatars', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('model_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('avatars', 'folder_name')
    # ### end Alembic commands ###
