"""Add sign contributions

Revision ID: 6d66a77db2cb
Revises: 05ecfdce2c98
Create Date: 2026-03-30 15:06:26.648535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d66a77db2cb'
down_revision: Union[str, Sequence[str], None] = '05ecfdce2c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sign_contributions_id'), 'sign_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_sign_contributions_title'), 'sign_contributions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_contributions_title'), table_name='sign_contributions')
    op.drop_index(op.f('ix_sign_contributions_id'), table_name='sign_contributions')
    op.drop_table('sign_contributions')
    # ### end Alembic commands ###
