"""Add attributes to avatar model

Revision ID: 755191257491
Revises: 92b279cf7c55
Create Date: 2026-03-17 15:27:36.525274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755191257491'
down_revision: Union[str, Sequence[str], None] = '92b279cf7c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('attributes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'attributes')
    # ### end Alembic commands ###
