"""Add description to signs

Revision ID: 7a07c2b779a4
Revises: 048f7915e811
Create Date: 2026-03-02 14:49:11.964279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a07c2b779a4'
down_revision: Union[str, Sequence[str], None] = '048f7915e811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signs', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signs', 'description')
    # ### end Alembic commands ###
