"""Change description to JSON

Revision ID: 80e066f711dc
Revises: 50fada1b0a58
Create Date: 2026-03-27 14:10:01.629652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e066f711dc'
down_revision: Union[str, Sequence[str], None] = '50fada1b0a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               postgresql_using='description::json', 
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signs', 'description',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
