"""Add daily challenge tracking

Revision ID: 92b279cf7c55
Revises: 9bb02796c4e4
Create Date: 2026-03-17 14:16:59.487450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b279cf7c55'
down_revision: Union[str, Sequence[str], None] = '9bb02796c4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_avatars', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_avatars', 'avatar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_stats', sa.Column('daily_challenge_progress', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('last_challenge_claim_date', sa.Date(), nullable=True))
    op.add_column('user_stats', sa.Column('current_challenge_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'current_challenge_id')
    op.drop_column('user_stats', 'last_challenge_claim_date')
    op.drop_column('user_stats', 'daily_challenge_progress')
    op.alter_column('user_avatars', 'avatar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_avatars', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
