"""Add last_claim_date for daily rewards

Revision ID: 958dbe3b12e5
Revises: e8ea1b8d248e
Create Date: 2026-03-10 14:51:35.531770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958dbe3b12e5'
down_revision: Union[str, Sequence[str], None] = 'e8ea1b8d248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('last_claim_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'last_claim_date')
    # ### end Alembic commands ###
