"""Add updated_at to user_progress

Revision ID: 9bb02796c4e4
Revises: d9ddf6be9746
Create Date: 2026-03-16 15:38:48.069734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb02796c4e4'
down_revision: Union[str, Sequence[str], None] = 'd9ddf6be9746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'updated_at')
    # ### end Alembic commands ###
