"""Add avatar table

Revision ID: b035af81a6f0
Revises: 9d89cb83ec3d
Create Date: 2026-02-27 14:00:18.215863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b035af81a6f0'
down_revision: Union[str, Sequence[str], None] = '9d89cb83ec3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_avatars_id'), 'avatars', ['id'], unique=False)
    op.drop_index(op.f('ix_signs_title'), table_name='signs')
    op.create_unique_constraint(None, 'signs', ['title'])
    op.drop_column('signs', 'model_url')
    op.drop_column('signs', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signs', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signs', sa.Column('model_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'signs', type_='unique')
    op.create_index(op.f('ix_signs_title'), 'signs', ['title'], unique=True)
    op.drop_index(op.f('ix_avatars_id'), table_name='avatars')
    op.drop_table('avatars')
    # ### end Alembic commands ###
