"""Fix avatar columns

Revision ID: bdf959abf7f9
Revises: 67a472721919
Create Date: 2026-02-27 14:27:03.625658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf959abf7f9'
down_revision: Union[str, Sequence[str], None] = '67a472721919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('model_url', sa.String(), nullable=False))
    op.add_column('avatars', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('avatars', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('avatars', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('avatars', 'folder_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('avatars_name_key'), 'avatars', type_='unique')
    op.create_index(op.f('ix_avatars_name'), 'avatars', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatars_name'), table_name='avatars')
    op.create_unique_constraint(op.f('avatars_name_key'), 'avatars', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('avatars', 'folder_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('avatars', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('avatars', 'is_active')
    op.drop_column('avatars', 'thumbnail_url')
    op.drop_column('avatars', 'model_url')
    # ### end Alembic commands ###
