"""Add weekly activity tracking

Revision ID: d9ddf6be9746
Revises: 958dbe3b12e5
Create Date: 2026-03-15 18:23:15.856115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ddf6be9746'
down_revision: Union[str, Sequence[str], None] = '958dbe3b12e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('weekly_activity', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'weekly_activity')
    # ### end Alembic commands ###
